obj-m += multiplier.o
all:
	make -C /home/grads/w/willytwsu/ECEN749_TW/Lab05/Lab04/linux-3.14 M=$(PWD) modules
clean:
	make -C /home/grads/w/willytwsu/ECEN749_TW/Lab05/Lab04/linux-3.14 M=$(PWD) clean
