# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/multiply/multiply.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply}]

# IP: bd/multiply/ip/multiply_processing_system7_0_0/multiply_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiply_processing_system7_0_0 || ORIG_REF_NAME==multiply_processing_system7_0_0}]

# IP: bd/multiply/ip/multiply_multiply_0_0/multiply_multiply_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiply_multiply_0_0 || ORIG_REF_NAME==multiply_multiply_0_0}]

# IP: bd/multiply/ip/multiply_processing_system7_0_axi_periph_0/multiply_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiply_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==multiply_processing_system7_0_axi_periph_0}]

# IP: bd/multiply/ip/multiply_rst_processing_system7_0_100M_0/multiply_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiply_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==multiply_rst_processing_system7_0_100M_0}]

# IP: bd/multiply/ip/multiply_auto_pc_0/multiply_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiply_auto_pc_0 || ORIG_REF_NAME==multiply_auto_pc_0}]

# XDC: bd/multiply/ip/multiply_processing_system7_0_0/multiply_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==multiply_processing_system7_0_0 || ORIG_REF_NAME==multiply_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/multiply/ip/multiply_rst_processing_system7_0_100M_0/multiply_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiply_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==multiply_rst_processing_system7_0_100M_0}]

# XDC: bd/multiply/ip/multiply_rst_processing_system7_0_100M_0/multiply_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiply_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==multiply_rst_processing_system7_0_100M_0}]

# XDC: bd/multiply/ip/multiply_rst_processing_system7_0_100M_0/multiply_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/multiply/ip/multiply_auto_pc_0/multiply_auto_pc_0_ooc.xdc

# XDC: bd/multiply/multiply_ooc.xdc
